Exam/examProject/urls.py
from django.contrib import admin
from . import views
from django.urls import path,include 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/',include('student.urls')),
    path('faculty/',include('faculty.urls')),
    path('student-pref/',include('studentPreferences.urls')),
    path('exams/',include('questions.urls')),
    path('',views.index,name = "homepage")
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Exam/faculty/urls.py
from django.urls import path
from .views import Register,LoginView,LogoutView
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',views.index,name="faculty-index"),
    path('register/',Register.as_view(),name = "faculty-register"),
    path('login/',LoginView.as_view(),name="faculty-login"),
    path('logout/',LogoutView.as_view(),name="faculty-logout"),
    path('reset-password/',auth_views.PasswordResetView.as_view(template_name="faculty/resetPassword.html"),name="password_reset_faculty"),
    path('reset-password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="faculty/resetPasswordSent.html"),name="password_reset_done_faculty"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="faculty/setNewPassword.html"),name="password_reset_confirm_faculty"),
    path('reset-password-complete/',auth_views.PasswordResetCompleteView.as_view(template_name="faculty/resetPasswordDone.html"),name="password_reset_complete_faculty"),
]

Exam/student/models.py
from django.db import models
from django.contrib.auth.models import User
from questions.question_models import Question_DB
from questions.questionpaper_models import Question_Paper

class StudentInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=200, blank=True)
    stream = models.CharField(max_length=50, blank=True)
    picture = models.ImageField(upload_to = 'student_profile_pics', blank=True)

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name_plural = 'Student Info'

class Stu_Question(Question_DB):
    professor = None
    student = models.ForeignKey(User, limit_choices_to={'groups__name': "Student"}, on_delete=models.CASCADE, null=True)
    choice = models.CharField(max_length=3, default="E")

    def __str__(self):
        return str(self.student.username) + " "+ str(self.qno) +"-Stu_QuestionDB"


class StuExam_DB(models.Model):
    student = models.ForeignKey(User, limit_choices_to={'groups__name': "Student"}, on_delete=models.CASCADE, null=True)
    examname = models.CharField(max_length=100)
    qpaper = models.ForeignKey(Question_Paper, on_delete=models.CASCADE, null=True)
    questions = models.ManyToManyField(Stu_Question)
    score = models.IntegerField(default=0)
    completed = models.IntegerField(default=0)

    def __str__(self):
        return str(self.student.username) +" " + str(self.examname) + " " + str(self.qpaper.qPaperTitle) + "-StuExam_DB"


class StuResults_DB(models.Model):
    student = models.ForeignKey(User, limit_choices_to={'groups__name': "Student"}, on_delete=models.CASCADE, null=True)
    exams = models.ManyToManyField(StuExam_DB)

    def __str__(self):
        return str(self.student.username) +" -StuResults_DB"

Exam/templates/exam/addquestionpaper.html
{% extends 'base_faculty.html' %}

{% block body %}
    <div class="mt-5">
    </div>

<style>
*{
  color: #745959;
}
button[type=submit]:hover{
        background: #87FF9B;
    }
#id_questions{
  display:block;
  width:100%;
  height:calc(10em);
  padding:.375rem .75rem;
  font-size:1rem;
  font-weight:400;
  line-height:1.5;
  color: #745959;
  background-color:#fff;
  background-clip:padding-box;
  border:1px solid #745959;
  border-radius:.25rem;
  transition:border-color .15s ease-in-out,box-shadow .15s ease-in-out;
    }
</style>
<div class="row">
	<div class="col-md-2"></div>
    <div class="col-md-6">
        <div class="ml-5 card">
            <form method="POST" action="{% url 'faculty-add_question_paper' %}">
                <div class="container">
                    {% csrf_token %}
                    {{examform.as_p}}
                </div>
                <div class="text-center">
                <button class= "btn" style="border-color:#745959; color:#745959;" type="submit">Submit</button>
                </div>
            </form>
        </div>
        </div>
</div>


{% endblock %}

Exam/templates/exam/addquestions.html
{% extends 'base_faculty.html' %}

{% block body %}
    <div class="mt-5">
    </div>

<style>
*{
  color: #745959;
}
button[type=submit]:hover{
        background: #87FF9B;
    }
    #id_questions{display:block;width:100%;height:calc(10em);padding:.375rem .75rem;font-size:1rem;font-weight:400;line-height:1.5;color:#745959;background-color:#fff;background-clip:padding-box;border:1px solid #745959;border-radius:.25rem;transition:border-color .15s ease-in-out,box-shadow .15s ease-in-out}
</style>
<div class="row">
	<div class="col-md-2"></div>
    <div class="col-md-6">
        <div class="ml-5 card">
            <form method="POST" action="{% url 'faculty-addquestions' %}">
                <div class="container">
                    {% csrf_token %}
                    {{examform.as_p}}
                </div>
                <div class="text-center">
                <button class= "btn" style="border-color:#745959; color:#745959;"type="submit">Submit</button>
                </div>
            </form>
        </div>
        </div>
</div>


{% endblock %}

Exam/templates/exam/attendance.html
{% extends 'base.html' %}

{% block body %}
<style media="screen">
  *{
    color:#745959;
  }
</style>
    <div class="mt-5">
    </div>
    <div class="container">
        {% if exams %}
                <table class="table">
                    <thead class="thead" style="background-color: #a3d5ff;">
                        <tr>
                        <th scope="col">Exam Name</th>
                        <th scope="col">Exam Professor</th>
                        <th scope="col">Attendance</th>
                        </tr>
                    </thead>
                {% for exam in exams %}
                        <tbody>
                            <tr>
                            <td>{{exam.name}}</td>
                            <td>{{exam.professor}}</td>
                            <td>Not Attended</tr>
                        </tbody>
                {% endfor %}
                </table>
        {% endif %}
    </div>
    <div class="container">
        {% if completed %}
                <table class="table">
                    <thead class="thead" style="background-color: #87ff9b">
                        <tr>
                        <th scope="col">Exam Name</th>
                        <th scope="col">Exam Professor</th>
                        <th scope="col">Attendance</th>
                        </tr>
                    </thead>
            {% for exam in completed %}
                    <tbody>
                        <tr>
                        <td>{{exam.name}}</td>
                        <td>{{exam.professor}}</td>
                        <td>
                            Attended
                        </tr>
                    </tbody>
                <input type="hidden" value="{{ exam }}" name="paper">
            {% endfor %}
            </table>
        {% endif %}
    </div>

{% endblock %}

Exam/templates/exam/giveExam.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exam Portal</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</head>
<body>
  <style media="screen">
  input[type=submit]:hover{
          background: #a3d5ff;
      }
  </style>
    <div class="container">
        <h2> Exam Name  - {{ exam.name }}</h2>
        <h2> Professor - {{ exam.professor }}</h2>
        <h2> Paper Name  - {{ exam.question_paper.qPaperTitle }}</h2>
        <h5>
            This Exam is of  {{ exam.total_marks }} marks
        </h5>
        <h5>
            <a>Time left : <a id="dmin">{{ min }}</a> mins <a id="dsec">{{ sec }}</a> seconds</a>
        </h5>
        <form method="POST" id="examform">
            {% csrf_token %}
            <ol>
                {% for ques in question_list %}

                <p>{{ ques.question }}</p>
                <input type="radio" id="optionA" name="{{ ques.question }}" value="A">
                <label for="optionA">{{ ques.optionA }}</label><br>
                <input type="radio" id="optionB" name="{{ ques.question }}" value="B">
                <label for="optionB">{{ ques.optionB }}</label><br>
                <input type="radio" id="optionC" name="{{ ques.question }}" value="C">
                <label for="optionC">{{ ques.optionC }}</label><br>
                <input type="radio" id="optionD" name="{{ ques.question }}" value="D">
                <label for="optionD">{{ ques.optionD }}</label><br>
                {% endfor %}
            </ol>
            <input type="hidden" value="{{ qpaper.qPaperTitle}}" name="papertitle">
            <input type="hidden" value="{{ exam }}" name="paper">
            <input type="hidden" id="secs" value="{{ secs }}">
            <input type="hidden" id="mins" value="{{ mins }}">
            <input type="hidden" id="professorname" value="{{ exam.professor }}">
            <input type="submit" value="Submit" id="PaperSubmit" onclick="submitFormOkay = true;" class = "btn" style="border-color:#745959; color:#745959;"/>
        </form>
        <script type="text/javascript">
        count = 0;
        $(document).ready(function() {
            var hidden, visibilityState, visibilityChange;

            if (typeof document.hidden !== "undefined") {
                hidden = "hidden", visibilityChange = "visibilitychange", visibilityState = "visibilityState";
            } else if (typeof document.msHidden !== "undefined") {
                hidden = "msHidden", visibilityChange = "msvisibilitychange", visibilityState = "msVisibilityState";
            }

            var document_hidden = document[hidden];

            document.addEventListener(visibilityChange, function() {
                if(document_hidden != document[hidden]) {
                if(document[hidden]) {
                    count+=1;
                    if(count == 5){
                        console.log("DONE")
                        mail()
                    }
                }
                document_hidden = document[hidden];
                }
            });
            });

            function mail(){
                var professorname = document.getElementById("professorname").value;
                fetch(`/student/cheat/${professorname}`,{
                    method:"GET",
                    credentials: "same-origin",
                    headers: {
                        "X-CSRFToken": getCookie("csrftoken"),
                        "Accept": "application/json",
                        "Content-Type": "application/json"
                    },
                })
            }
            
        window.onbeforeunload = function() { return "Your work will be lost."; };
        var milisec = 0;
        var seconds = document.getElementById("secs").value;
        var minutes = document.getElementById("mins").value
        function display() {
            if (minutes == 0 && seconds == 0) {
                window.onbeforeunload = undefined
                document.getElementById("examform").submit();
            }
            if (seconds == 0) {
                minutes = minutes - 1
                seconds = 60
            }
            seconds -= 1
            document.getElementById("dsec").innerHTML = seconds
            document.getElementById("dmin").innerHTML = minutes
            setTimeout("display()", 1000)
        }
        display()
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
    </script>
    </div>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>

Exam/templates/exam/mainexam.html
{% extends 'base_faculty.html' %}

{% block body %}
    <div class="mt-5">
    </div>

<style>
    *{
      color:#745959;
    }
    #id_question_paper{display:block;width:100%;height:calc(1.5em + .75rem + 2px);padding:.375rem .75rem;font-size:1rem;font-weight:400;line-height:1.5;color:#745959;background-color:#fff;background-clip:padding-box;border:1px solid #ced4da;border-radius:.25rem;transition:border-color .15s ease-in-out,box-shadow .15s ease-in-out}
    button[type=submit]:hover{
            background: #87FF9B;
        }
</style>
<div class="row">
	<div class="col-md-2"></div>
    <div class="col-md-6">
        <div class="ml-5 card">
            <form method="POST" action="{% url 'view_exams' %}">
                <div class="container">
                    {% csrf_token %}
                    {{examform.as_p}}
                </div>
                <div class="text-center">
                <button class= "btn"type="submit" style="border-color:#745959; color:#745959;">Submit</button>
                </div>
            </form>
        </div>
        </div>
</div>


{% endblock %}

Exam/templates/exam/mainexamstudent.html
{% extends 'base.html' %}
{% load static %}

{% block css_block %}
<link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
{% endblock %}

{% block body %}
    <style>
        img{
        height:15em;
        width:5em;
      }
    </style>
    <div class="mt-5">
    </div>
    <div class="container">
            <div class="row">
                {% if exams %}
                    {% for exam in exams %}
                        <div class="card col-md-3 mt-3 ml-3 text-center" style="width: 18rem;">
                            <img class="card-img-top" src="{% static 'img/book.png' %}">
                            <div class="card-body">
                                <h5 class="card-title">{{exam.name}}</h5>
                                <p class="card-text text-center">Professor {{exam.professor}}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item text-center">Question Paper - {{exam.question_paper.qPaperTitle}}</li>
                            </ul>
                            <div class="card-body text-center">
                                <a onclick = window.open("{% url 'appear-exam' exam.id  %}","","width=800,height=800") target="_blank" class="btn btn-outline-danger">Appear</a>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
            <div class="jumbotron col-md-12 text-center bg-success">
                NO PENDING EXAMS
            </div>
        {% endif %}
            </div>
    </div>
    


{% endblock %}


          

Exam/templates/exam/previousexam.html
{% extends 'base_faculty.html' %}

{% block body %}
    <div class="mt-5">
    </div>

<div class="row">
	<div class="col-md-2"></div>
    <div class="col-md-6">
    <div class="ml-5 container">
        {% if exams %}
                <table class="table">
                    <thead class="thead" style="color: #745959; background-color: #87ff9b">
                        <tr>
                        <th scope="col">Exam Name</th>
                        <th scope="col">Exam Professor</th>
                        <th scope="col">Exam Total Marks</th>
                        </tr>
                    </thead>
                {% for exam in exams %}
                        <tbody>
                            <tr>
                            <td>{{exam.name}}</td>
                            <td>{{exam.professor}}</td>
                            <td>{{exam.total_marks}}</td>
                            </tr>
                        </tbody>
                {% endfor %}
                </table>
        {% else %}
            <div class="jumbotron text-center bg-success">
                NO EXAMS CREATED
            </div>
        {% endif %}
    </div>


{% endblock %}

Exam/templates/exam/previousstudent.html
{% extends 'base.html' %}

{% block body %}
    <div class="mt-5">
    </div>
    <div class="container">
        {% if completed %}
                <table class="table">
                    <thead class="thead" style="color: #745959; background-color: #87ff9b">
                        <tr>
                        <th scope="col">Exam Name</th>
                        <th scope="col">Exam title</th>
                        <th scope="col">Exam Professor</th>
                        <th scope="col">Action</th>
                        </tr>
                    </thead>
            {% for exam in completed %}
                    <tbody>
                        <tr>
                        <td>{{exam.name}}</td>
                        <td>{{exam.question_paper.qPaperTitle}}</td>
                        <td>{{exam.professor}}</td>
                        <td>
                            <a href="{% url 'result' exam.id  %}" class="btn btn-sm btn-info">Result</a>
                        </tr>
                    </tbody>
                <input type="hidden" value="{{ exam }}" name="paper">
            {% endfor %}
            </table>
        {% else %}
            <div class="jumbotron col-md-12 text-center bg-success">
                NO EXAMS
            </div>
        {% endif %}
    </div>

{% endblock %}

Exam/templates/exam/result.html
{% extends 'base.html' %}    

{% block body %}
    <div class="mt-5">
    </div>
    <div class="container">
        
        <table class="table">
            <thead class="thead-dark">
                <tr>
                <th scope="col">Exam Professor</th>
                <th scope="col">Exam Name</th>
                <th scope="col">Exam Title</th>
                <th scope="col">Marks Obtained</th>
                <th scope="col">Total Marks</th>
                </tr>
            </thead>
                <tbody>
                    <tr>
                    <td>{{exam.professor}}</td>
                    <td>{{exam.name}}</td>
                    <td>{{exam.question_paper.qPaperTitle}}</td>
                    <td>{{score}}</td>
                    <td>{{exam.total_marks}}</td>
                    </tr>
                </tbody>
        </table>
    </div>
    
{% endblock %}

Exam/templates/exam/resultsstudent.html
{% extends 'base_faculty.html' %}

{% block body %}
    <div class="mt-5">
    </div>

<div class="row">
	<div class="col-md-1"></div>
    <div class="col-md-8">
    <div class="ml-5 container">
        {% if students %}
                <table class="table">
                    <thead class="thead" style="color: #745959; background-color: #87ff9b">
                        <tr>
                        <th scope="col">Student Name</th>
                        <th scope="col">Scores of Exams Attended</th>
                        </tr>
                    </thead>
                {% for key, values in students.items %}
                        <tbody>
                            <tr>
                                <td>{{key}}</td>
                                <td>{{values}}</td>
                            </tr>
                        </tbody>
                {% endfor %}
                </table>
        {% else %}
            <div class="jumbotron text-center bg-success">
                NO STUDENT EXIST IN DATABASE
            </div>
        {% endif %}
    </div>


{% endblock %}

Exam/templates/exam/viewstudents.html
{% extends 'base_faculty.html' %}

{% block body %}
    <div class="mt-5">
    </div>

<div class="row">
	<div class="col-md-1"></div>
    <div class="col-md-7">
    <div class="ml-5 container">
        {% if students %}
                <table class="table">
                    <thead class="thead" style="color: #745959; background-color: #87ff9b">
                        <tr>
                        <th scope="col">Student Name</th>
                        <th scope="col">Exams Attended</th>
                        </tr>
                    </thead>
                {% for key, values in students.items %}
                        <tbody>
                            <tr>
                                <td>{{key}}</td>
                                <td>{{values}}</td>
                            </tr>
                        </tbody>
                {% endfor %}
                </table>
        {% else %}
            <div class="jumbotron text-center bg-success">
                NO STUDENT EXIST IN DATABASE
            </div>
        {% endif %}
    </div>


{% endblock %}